# Generated by Django 4.1.1 on 2022-09-17 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_subject_enrolled_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
