name: Testing
on: push

jobs:
  test_project
  steps:
  - uses: actions/checout@v2
  - name: Run Django unit tests
    run: |
    pip install --user -r requirements.txt
    python manage.py makemigrations
    python manage.py migrate
    coverage run --source='.' manage.py test
    coverage report
